import json
from typing import Any, AsyncIterator, Dict, Iterator, List, Mapping, Optional, Union, Tuple

from langchain_core.callbacks import (
    AsyncCallbackManagerForLLMRun,
    CallbackManagerForLLMRun,
)
from langchain_core.language_models.llms import LLM
from langchain_core.outputs import GenerationChunk
from langchain_core.utils import get_from_dict_or_env, pre_init
from pydantic import ConfigDict, Field

DEFAULT_MODEL_ID = "klusterai/Meta-Llama-3.1-8B-Instruct-Turbo"


class KlusterAI(LLM):
    """KlusterAI models.

    To use, you should have the environment variable ``KLUSTERAI_API_KEY``
    set with your API token, or pass it as a named parameter to the
    constructor.

    Example:
        .. code-block:: python

            from langchain_community.llms import KlusterAI
            ka = KlusterAI(model_id="klusterai/Meta-Llama-3.1-8B-Instruct-Turbo",
                           klusterai_api_key="my-api-key")
    """

    model_id: str = DEFAULT_MODEL_ID
    model_kwargs: Optional[Dict] = None

    klusterai_api_key: Optional[str] = None

    client: Any = Field(default=None, exclude=True)  #: :meta private:
    async_client: Any = Field(default=None, exclude=True)  #: :meta private:

    request_timeout: Union[float, Tuple[float, float], Any, None] = None
    """Timeout for requests to KlusterAI API."""

    max_retries: int = 6
    """Maximum number of retries to make when generating."""

    model_config = ConfigDict(
        extra="forbid",
    )

    @pre_init
    def validate_environment(cls, values: Dict) -> Dict:
        """Validate that api key and python package exists in environment."""
        klusterai_api_key = get_from_dict_or_env(
            values, "klusterai_api_key", "KLUSTERAI_API_KEY"
        )
        values["klusterai_api_key"] = klusterai_api_key

        try:
            import openai
        except ImportError:
            raise ImportError(
                "Could not import openai python package. "
                "Please install it with `pip install openai`."
            )

        # Initialize the OpenAI client if not already provided
        if not values.get("client"):
            values["client"] = openai.OpenAI(
                api_key=klusterai_api_key,
                base_url="https://api.kluster.ai/v1",
                timeout=values.get("request_timeout"),
                max_retries=values.get("max_retries", 6),
            ).chat.completions

        if not values.get("async_client"):
            values["async_client"] = openai.AsyncOpenAI(
                api_key=klusterai_api_key,
                base_url="https://api.kluster.ai/v1",
                timeout=values.get("request_timeout"),
                max_retries=values.get("max_retries", 6),
            ).chat.completions

        return values

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters."""
        return {
            **{"model_id": self.model_id},
            **{"model_kwargs": self.model_kwargs},
        }

    @property
    def _llm_type(self) -> str:
        """Return type of llm."""
        return "klusterai"

    def _get_parameters(self, prompt: str, stop: Optional[List[str]] = None, **kwargs: Any) -> Dict:
        """Get the parameters for the API call."""
        model_kwargs = self.model_kwargs or {}
        merged_kwargs = {**model_kwargs, **kwargs}

        if stop:
            merged_kwargs["stop"] = stop

        params = {
            "model": self.model_id,
            "messages": [{"role": "user", "content": prompt}],
            **merged_kwargs,
        }

        return params

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call out to KlusterAI's API endpoint using OpenAI client.

        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.

        Returns:
            The string generated by the model.

        Example:
            .. code-block:: python

                response = ka("Tell me a joke.")
        """
        params = self._get_parameters(prompt, stop, **kwargs)

        try:
            response = self.client.create(**params)
            return response.choices[0].message.content
        except Exception as e:
            if hasattr(e, "status_code"):
                status_code = getattr(e, "status_code")
                self._handle_error_response(status_code, str(e))
            raise e

    async def _acall(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Async call to KlusterAI's API endpoint using OpenAI client."""
        params = self._get_parameters(prompt, stop, **kwargs)

        try:
            response = await self.async_client.create(**params)
            return response.choices[0].message.content
        except Exception as e:
            if hasattr(e, "status_code"):
                status_code = getattr(e, "status_code")
                self._handle_error_response(status_code, str(e))
            raise e

    def _stream(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> Iterator[GenerationChunk]:
        """Stream response from KlusterAI API using OpenAI client."""
        params = self._get_parameters(prompt, stop, **kwargs)
        params["stream"] = True

        try:
            for chunk in self.client.create(**params):
                if len(chunk.choices) > 0:
                    choice = chunk.choices[0]
                    if choice.delta.content is not None:
                        chunk_content = choice.delta.content
                        generation_chunk = GenerationChunk(text=chunk_content)
                        if run_manager:
                            run_manager.on_llm_new_token(chunk_content)
                        yield generation_chunk
        except Exception as e:
            if hasattr(e, "status_code"):
                status_code = getattr(e, "status_code")
                self._handle_error_response(status_code, str(e))
            raise e

    async def _astream(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> AsyncIterator[GenerationChunk]:
        """Async stream response from KlusterAI API using OpenAI client."""
        params = self._get_parameters(prompt, stop, **kwargs)
        params["stream"] = True

        try:
            async for chunk in await self.async_client.create(**params):
                if len(chunk.choices) > 0:
                    choice = chunk.choices[0]
                    if choice.delta.content is not None:
                        chunk_content = choice.delta.content
                        generation_chunk = GenerationChunk(text=chunk_content)
                        if run_manager:
                            await run_manager.on_llm_new_token(chunk_content)
                        yield generation_chunk
        except Exception as e:
            if hasattr(e, "status_code"):
                status_code = getattr(e, "status_code")
                self._handle_error_response(status_code, str(e))
            raise e

    def _handle_error_response(self, status_code: int, error_message: str) -> None:
        """Handle error responses from the API."""
        if status_code >= 500:
            raise Exception(f"KlusterAI Server Error: {error_message}")
        elif status_code == 401:
            raise Exception("KlusterAI Server: Unauthorized")
        elif status_code == 403:
            raise Exception("KlusterAI Server: Forbidden")
        elif status_code == 404:
            raise Exception(f"KlusterAI Server: Model not found {self.model_id}")
        elif status_code == 429:
            raise Exception("KlusterAI Server: Rate limit exceeded")
        elif status_code >= 400:
            raise ValueError(f"KlusterAI received an invalid payload: {error_message}")
        else:
            raise Exception(
                f"KlusterAI returned an unexpected response with status {status_code}: {error_message}"
            )
